language: node_js
node_js:
  - '13'
install:
  - yarn install --frozen-lockfile
script:
  - yarn run build
  - yarn run lint
  - yarn run test
deploy:
  provider: npm
  email: info@pascal-iske.de
  api_key:
    secure: YMKsBjrP8Hl1tbp5hcDPCNMgbkZOYvQEmRgaNKH9dHJ7QISF5q/xC47oR5qL/bRsYBhOBrLIMIx26wUgF3NGVykiTNOUHaP4ZJm27z1b3HTiH9k3c7z6fNeQQwyzswptPMjMO8V0xHgNKuMU/fl0BM+sWhlgUzBc9JWkvrE6onQ9s07p1BpQ930TxpqhIR29bwbXnUyDIgxFOVPjP2fSe4cv8podQA4R6JjQbE3QPlNXUMF5PbRLWRipdt0aVH6oRe2VFWy9x5nsqTLW+SHitQgvu11S8nK21AmK7npwm++RSSRxGk/dB8zZCy6dSWaXBgnRd23xoIHCgBbW0EAUfYv5P0U1RtKb9P2s4ucIHsViTsuJlzwsNQobNT1dAHZPE+qSyIoQ5kRi2BaTmc3xikSBH5sdRE6O3R4DXF/zRr6gM28+uHI+mVjNKG9zf58VrG8htaEbbbHo5r+C6/UxWWr+HmkBGmJRXjcwf2IwqDnkov/ssEyYSfZC3oHaiQDyWTbvP838HsCov3SJ20SeuCEltTAN6NgSBscbTcI+QsXRgEXDxH0kdziQgeaezwp3C20o2ae17bhhIZln4GL0/plbzrI21/wC7uLtBBkD8r05zkanqQN2vRhy3/HIFz27KkwPI2ofLceXxKFRvOH5EUbDIRI57KsjUIXQmozG72w=
  skip_cleanup: true
  on:
    tags: true
    branch: master
    node: 13
