language: node_js
node_js:
  - '10'
  - '9'
  - '8'
before_install: yarn global add greenkeeper-lockfile@1
install:
  - yarn install
  - yarn run build
before_script: greenkeeper-lockfile-update
script:
  - yarn run lint
  - yarn run test
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  email: info@pascal-iske.de
  api_key:
    secure: YMKsBjrP8Hl1tbp5hcDPCNMgbkZOYvQEmRgaNKH9dHJ7QISF5q/xC47oR5qL/bRsYBhOBrLIMIx26wUgF3NGVykiTNOUHaP4ZJm27z1b3HTiH9k3c7z6fNeQQwyzswptPMjMO8V0xHgNKuMU/fl0BM+sWhlgUzBc9JWkvrE6onQ9s07p1BpQ930TxpqhIR29bwbXnUyDIgxFOVPjP2fSe4cv8podQA4R6JjQbE3QPlNXUMF5PbRLWRipdt0aVH6oRe2VFWy9x5nsqTLW+SHitQgvu11S8nK21AmK7npwm++RSSRxGk/dB8zZCy6dSWaXBgnRd23xoIHCgBbW0EAUfYv5P0U1RtKb9P2s4ucIHsViTsuJlzwsNQobNT1dAHZPE+qSyIoQ5kRi2BaTmc3xikSBH5sdRE6O3R4DXF/zRr6gM28+uHI+mVjNKG9zf58VrG8htaEbbbHo5r+C6/UxWWr+HmkBGmJRXjcwf2IwqDnkov/ssEyYSfZC3oHaiQDyWTbvP838HsCov3SJ20SeuCEltTAN6NgSBscbTcI+QsXRgEXDxH0kdziQgeaezwp3C20o2ae17bhhIZln4GL0/plbzrI21/wC7uLtBBkD8r05zkanqQN2vRhy3/HIFz27KkwPI2ofLceXxKFRvOH5EUbDIRI57KsjUIXQmozG72w=
  skip_cleanup: true
  on:
    tags: true
    branch: master
    node: 9
env:
  global:
    secure: BtWq0vnVbfQFR7B2DBhI4QUni/yQz4kjkL4n76w82CxrzTCEJJQYrARZSAjO3eoyoj5fL7aK47qQFZaRW6hm0Z/t9T3YwAYS4oRm1+/ePYqoAf8H3LnJP1wbUpemFIjkgGKQ/nOqMmhsi0YjzMO30+r+YqfRQTSdKxG4v5IEYoa5KlQbTcD6PDcegGuYVm5H8XiP5Z0q0t9DgFPd7NMWDmD1CYJGlALH/ORf4U6BmmM7gwtCLPpyP1OIQyz3ybN1EiakY2fn/08d39j21F4a6bagdGq7bnPby2b0HN0pBaiSRpwf1F9AizDpbHPGshypk4buVcsJSsOnl7kSlcuFCjQJestO3RDs3IIpt4RwW/GwWBwTz/6IVCYwHeCVNQlUgS0XWVE9UC9nW5NYF2F2t4AiqglS35kzNaFLt8eYhqpnOJNxNQI1JFQhHh5IxCihEuFG64VXl1ZAEHoOw9UCa6eiwlFhWVmA8gABgHvyW2jqf/66G9iHYdRzsRDvu1ThlFdqrr14BmTRY1KlrKTIGydLGhMtQAB8WTCUlhC586GBiZ8NgvuDKT9MX/iUpwGi8VzNwxcUpG5YkAhbkYsxdDNkZ0hlYGiE4Zwm4SOAU0KptMLDMh4OLYRkyUqPO0/8Bc/EenoJ7lhFJ/xCmgkoIpCFQfAcQ03rAZPZAsyk47o=
